[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.1"
dioxus-core = "0.3.0"
dioxus-desktop = "0.3.0"
dioxus-hooks = "0.3.0"
dioxus-html = "0.3.0"
dioxus-heroicons = { git="https://github.com/Satellite-im/dioxus-heroicons", branch = "dioxus-nightly" }
timeago = "0.4.0"
humansize = "2.0.0"
unic-langid = "0.9.1"
isolang = "2.2.0"
fluent-templates = "0.8.0"
warp = { git = "https://github.com/Satellite-im/Warp", rev = "ed3b5de968fb623a7d76170a5d7dd3f3c79d3e1b"}
